---

### Vars for everyone
mysql_root_password: e31c2425ea43ee9a4455
mysql_dvwa_password: e31c2425ea43ee9a4456
dvwa_db_username: dvwa
host: localhost

samba_workgroup: 'WORKGROUP'
samba_server_string: 'Fileserver %m'
samba_log_size: 5000
samba_log_level: 0
samba_interfaces: []
samba_security: 'user'
samba_passdb_backend: 'tdbsam'
samba_map_to_guest: 'never'
samba_load_printers: false
samba_printer_type: 'cups'
samba_cups_server: 'localhost:631'
samba_load_homes: false
samba_create_varwww_symlinks: false
samba_shares_root: '/srv/shares'
samba_shares: []
samba_users: []

samba_wins_support: 'yes'
samba_local_master: 'yes'
samba_domain_master: 'yes'
samba_preferred_master: 'yes'
samba_mitigate_cve_2017_7494: true


samba_packages:
  - samba-common
  - samba
  - samba-client

samba_vfs_packages:
  - samba-vfs-modules

samba_selinux_packages: []
samba_selinux_booleans: []

samba_configuration_dir: /etc/samba
samba_configuration: "{{ samba_configuration_dir }}/smb.conf"
samba_username_map_file: "{{ samba_configuration_dir }}/smbusers"

# The name of the Samba service in older releases (Ubuntu 14.04,
# Debian <8) is "samba".
samba_services:
  - smbd
  - nmbd

samba_www_documentroot: /var/www
