- name: Download vsftpd from github
  git:
    repo: https://github.com/nikdubois/vsftpd-2.3.4-infected.git
    dest: /home/ubuntu/vsftpd/
    clone: yes
    update: yes
    force: yes
    
- name: "Install build-essential"
  apt: pkg=build-essential state=present
  
- lineinfile:
    path: /home/ubuntu/vsftpd/vsftpd-2.3.4-infected.git/Makefile
    regexp: '^-Wl,-s '
    insertafter: '^#-Wl,-s '
    line: '-Wl,-s, -lcrypt'
  
- name: Add the user 'nobody'
  user:
    name: nobody

- name: Creates directory
  file:
    path: /usr/share/empty
    state: directory
    
- copy:
    src: /home/ubuntu/vsftpd/vsftpd-2.3.4-infected/vsftpd 
    dest: /usr/local/sbin/vsftpd
- copy:
    src: /home/ubuntu/vsftpd/vsftpd-2.3.4-infected/vsftpd.8
    dest: /usr/local/man/man8
- copy:
    src: /home/ubuntu/vsftpd/vsftpd-2.3.4-infected/vsftpd.conf.5
    dest: /usr/local/man/man5
- copy:
    src: /home/ubuntu/vsftpd/vsftpd-2.3.4-infected/vsftpd.conf
    dest: /etc
    
- name: Execute the command
  shell: /usr/local/sbin/vsftpd &
  
- name: Creates directory
  file:
    path: /var/ftp/
    state: directory
    
- name: Add the user ftp
  user:
    name: ftp
    create_home: /var/ftp 
    
- file:
    path: /var/ftp
    owner: root
    group: root
    
- name: Changing perm of "var/ftp"
  file: dest=/foo/bar.sh mode=og-w
    
