- name: Adding the repository key to the repository
  shell: |
    wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
    sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -sc)-pgdg main" > /etc/apt/sources.list.d/PostgreSQL.list'
- name: installing shit
  shell: apt-get -yq install postgresql-10 

- name: Copying postgresql configuration file
  copy:
    src: /etc/ansible/roles/additional/templates/postgresql.conf
    dest: /etc/postgresql/10/main/
