---
- hosts: windows
  gather_facts: no
  tasks:
  - name: Install Web-WebServer
    win_feature:
      name: Web-Server
  - name: Install File and storage services
    win_feature:
      name: FileAndStorage-Services
      name: File-Services
      name: FS-FileServer
      name: FS-SyncShareService
      state: present
  - name: Install DNS
    win_feature:
      name: DNS
      
