---
- hosts: windows
  gather_facts: no
  tasks:
  - name: Install (IIS) Web-WebServer
    win_feature:
      name: Web-Server
      name: Web-Mgmt-Tools
      name: Web-Mgmt-Console
      state: present
  - name: Install File and storage services
    win_feature:
      name: FileAndStorage-Services
      name: File-Services
      name: FS-FileServer
      name: FS-SyncShareService
      state: present
  - name: Install FTP
    win_feature:
      name: Web-Ftp-Server
      name: Web-Ftp-Service
      state: present
  - name: Install SMTP
    win_feature:
      name: SMTP-Server
      name: FS-SMB1
      name: FS-SMB1-SERVER
      state: present
  - name: Install DNS
    win_feature:
      name: DNS
      state: present
