---
- name: Installing DVWA
  hosts: 192.168.1.4
  remote_user: ansible
  become: true
  become_method: sudo

  roles:
    - common
    - web
    - db
    - php
    
 - name: Install DVWA
  hosts: 192.168.1.6
  remote_user: ansible
  become: true
  become_method: sudo

  roles:
    - additional

