---
- hosts: windows
  gather_facts: no
  tasks:
  - name: Install File and storage services
    win_feature:
      name: FileAndStorage-Services
      name: File-Services
      name: FS-FileServer
      name: FS-SyncShareService
      state: present
  - name: Start share sync
    win_service:
      name: SyncShareSvc
      state: started
  - name: Install SMB1
    win_feature:
      name: FS-SMB1
      state: present
- hosts: Win1
  gather_facts: no
  tasks:
  - name: Install (IIS) Web-WebServer
    win_feature:
      name: Web-Server
      name: Web-Mgmt-Tools
      name: Web-Mgmt-Console
      state: present
  - name: Install FTP
    win_feature:
      name: Web-Ftp-Server
      name: Web-Ftp-Service
      state: present
  - name: Run IIS web server
    win_service:
      name: W3Svc
      state: started
  - name: Create website
    win_copy:
      content: "<html><head><title>This is a website!</title></head><body><h1>But it's just an example. However this could be a legitimate website being screengrabed. This is just an example tho...</h1><p>This is a paragraph.</p></body></html>"
      dest: C:\Inetpub\wwwroot\index.html
  - name: Install SMB server and client
    win_feature:
      name: FS-SMB1-CLIENT
      name: FS-SMB1-SERVER
  - name: Configure and start FTP
    win_shell: |
      Import-Module WebAdministration
      $ftpsitename = "FTPserver"
      $path = "C:\Users\ansibleuser\Desktop\FTPserver"
      mkdir $path
      New-WebFtpSite -Name $ftpsitename -Port 21 -PhysicalPath $path
      $param = @{
             Path    = 'C:\Users\ansibleuser\Desktop\FTPserver'
             Name    = 'ftpserver.security.authentication.basicauthentication.disabled'
             Value   = $true
             Verbose = $True
      }
- hosts: Win2
  gather_facts: no
  tasks:
  - name: Install SMB server and client
    win_feature:
      name: FS-SMB1-CLIENT
      name: FS-SMB1-SERVER
      state: present
- hosts: Win3
  gather_facts: no
  tasks:
  - name: Install DNS
    win_feature:
      name: DNS
      state: present
