---
- hosts: Win1
  gather_facts: no
  tasks:
  - name: Install IIS Web-Server with sub features and management tools
    ansible.windows.win_feature:
      name: Web-Server
      state: present
    register: win_feature
  - name: Reboot if installing Web-Server feature requires it
    ansible.windows.win_reboot:
    when: win_feature.reboot_required
  - name: Install rest
    ansible.windows.win_feature:
      name: Web-WebServer
      name: Web-Mgmt-Tools
      name: Web-Mgmt-Console
      state: present
    register: win_feature
  - name: Reboot if installing Web-Server feature requires it again
    ansible.windows.win_reboot:
    when: win_feature.reboot_required
  - name: Create website
    win_copy:
      src: websites/index1.html
      dest: C:\Inetpub\wwwroot\index.html
      remote_src: no
  - name: Run IIS web server
    win_service:
      name: W3Svc
      state: started
  - name: Copy SSL cert to Windows
    win_copy:
      src: websites/cert.pfx
      dest: C:\Users\ansibleuser\Desktop\cert.pfx
      remote_src: no
  - name: Import cert to IIS
    ansible.windows.win_certificate_store:
      path: C:\Users\ansibleuser\Desktop\cert.pfx
      state: present
      password: "@nsib1epaSsw0rd"
    become: yes
    become_method: runas
    become_user: ansibleuser
  - name: Add a HTTPS binding
    community.windows.win_iis_webbinding:
      name: Default Web Site
      protocol: https
      port: 443
      ip: "*"
      certificate_hash: 8978622c9ddcf0e9f6e1f6b3955295359cab7915
      state: present
  - name: Install RPC
    ansible.windows.win_feature:
      name: RPC-over-HTTP-Proxy
      state: present
  - name: Install SMB 1
    ansible.windows.win_feature:
      name: FS-SMB1
      name: FS-SMB1-SERVER
      state: present
  - name: SNMP-Service
    ansible.windows.win_feature:
      name: SNMP-Service
      state: present
- hosts: Win2
  gather_facts: no
  tasks:
  - name: Install DNS and DHCP
    ansible.windows.win_feature:
      name: DNS
      name: DHCP
      state: present
  - name: Install IIS
    ansible.windows.win_feature:
      name: Web-Server
      state: present
    register: win_feature
  - name: Reboot if installing Web-Server feature requires it
    ansible.windows.win_reboot:
    when: win_feature.reboot_required
  - name: Install rest
    ansible.windows.win_feature:
      name: Web-Mgmt-Tools
      name: Web-Mgmt-Console
      name: Web-Ftp-Server
      name: Web-Ftp-Service
      state: present
    register: win_feature
  - name: Reboot win2
    ansible.windows.win_reboot:
    when: win_feature.reboot_required
  - name: Configure and start FTP
    win_shell: |
      Import-Module WebAdministration
      $ftpsitename = "FTPfolder"
      $path = "C:\Users\ansibleuser\Desktop\FTPfolder"
      mkdir $path
      New-WebFtpSite -Name $ftpsitename -Port 21 -PhysicalPath $path
      $param = @{
             Path    = 'C:\Users\ansibleuser\Desktop\FTPfolder'
             Name    = 'ftpserver.security.authentication.basicauthentication.disabled'
             Value   = $true
             Verbose = $True
      }
  - name: Make sure IIS webserver not running
    win_service:
      name: W3Svc
      state: stopped
  - name: Run FTP
    win_service:
      name: ftpsvc
      state: started
  - name: Download Apache 2.4.46
    win_get_url:
      url: https://www.apachelounge.com/download/VS16/binaries/httpd-2.4.46-win64-VS16.zip
      dest: C:\Users\ansibleuser\Desktop\Apache.zip
  - name: Unzipping Apache
    community.windows.win_unzip:
      src: C:\Users\ansibleuser\Desktop\Apache.zip
      dest: C:\
      delete_archive: yes
  - name: Install Apache
    script: InstallApacheOnWindows.bat
  - name: Deleting Apache default index.html
    ansible.windows.win_file:
      path: C:\Apache24\htdocs\index.html
      state: absent
  - name: Create new website
    win_copy:
      src: websites/index2.html
      dest: C:\Apache24\htdocs\index.html
      remote_src: no
  - name: Open firewall
    community.windows.win_firewall_rule:
      name: Allow Apache (by Ansible)
      description: Created by Ansible.
      program: C:\Apache24\bin\httpd.exe
      localport: 80
      action: allow
      direction: in
      protocol: tcp
      state: present
      enabled: yes
  - name: Run Apache service
    win_service:
      name: Apache2.4
      state: started
