---
- hosts: Win1
  gather_facts: no
  tasks:
  - name: Install IIS Web-Server with sub features and management tools
    ansible.windows.win_feature:
      name: Web-Server
      state: present
    register: win_feature
  - name: Reboot if installing Web-Server feature requires it
    ansible.windows.win_reboot:
    when: win_feature.reboot_required
  - name: Install rest
    ansible.windows.win_feature:
      name: Web-WebServer
      name: Web-Mgmt-Tools
      name: Web-Mgmt-Console
      state: present
    register: win_feature
  - name: Reboot if installing Web-Server feature requires it again
    ansible.windows.win_reboot:
    when: win_feature.reboot_required
  - name: Create website
    win_copy:
      content: "<html><head><title>This is a website!</title></head><body><h1>But it's just an example. However this could be a legitimate website being screengrabed. This is just an example tho...</h1><p>This is a paragraph.</p></body></html>"
      dest: C:\Inetpub\wwwroot\index.html
  - name: Run IIS web server
    win_service:
      name: W3Svc
      state: started
- hosts: Win2
  gather_facts: no
  tasks:
  - name: Install IIS
    ansible.windows.win_feature:
      name: Web-Server
      state: present
    register: win_feature
  - name: Reboot if installing Web-Server feature requires it
    ansible.windows.win_reboot:
    when: win_feature.reboot_required
  - name: Install rest
    ansible.windows.win_feature:
      name: Web-Mgmt-Tools
      name: Web-Mgmt-Console
      name: Web-Ftp-Server
      name: Web-Ftp-Service
      state: present
    register: win_feature
  - name: Reboot win2
    ansible.windows.win_reboot:
  - name: Configure and start FTP
    win_shell: |
      Import-Module WebAdministration
      $ftpsitename = "test2"
      $path = "C:\Users\ansibleuser\Desktop\test2"
      mkdir $path
      New-WebFtpSite -Name $ftpsitename -Port 21 -PhysicalPath $path
      $param = @{
             Path    = 'C:\Users\ansibleuser\Desktop\test2'
             Name    = 'ftpserver.security.authentication.basicauthentication.disabled'
             Value   = $true
             Verbose = $True
      }
  - name: Run IIS web server
    win_service:
      name: W3Svc
      state: started
