---
- hosts: Win1
  gather_facts: no
  tasks:
  - name: Install IIS Web-Server with sub features and management tools
    ansible.windows.win_feature:
      name: Web-Server
      state: present
    register: win_feature
  - name: Reboot if installing Web-Server feature requires it
    ansible.windows.win_reboot:
    when: win_feature.reboot_required
  - name: Install rest
    ansible.windows.win_feature:
      name: Web-WebServer
      name: Web-Mgmt-Tools
      name: Web-Mgmt-Console
      state: present
    register: win_feature
  - name: Reboot if installing Web-Server feature requires it again
    ansible.windows.win_reboot:
    when: win_feature.reboot_required
  - name: Create website
    win_copy:
      content: "<html><head><title>This is a website!</title></head><body><h1>Webpage example. Screengrab me! <img src='https://upload.wikimedia.org/wikipedia/commons/f/ff/Cliche_Hacker_and_Binary_Code_%2826946304530%29.jpg'></h1><p>This is a paragraph.</p></body></html>"
      dest: C:\Inetpub\wwwroot\index.html
  - name: Run IIS web server
    win_service:
      name: W3Svc
      state: started
  - name: Install RPC
    ansible.windows.win_feature:
      name: RPC-over-HTTP-Proxy
      state: present
  - name: Install SMB 1
    ansible.windows.win_feature:
      name: FS-SMB1
      name: FS-SMB1-SERVER
      state: present
  - name: SNMP-Service
    ansible.windows.win_feature:
      name: SNMP-Service
      state: present
- hosts: Win2
  gather_facts: no
  tasks:
  - name: Install DNS and DHCP
    ansible.windows.win_feature:
      name: DNS
      name: DHCP
      state: present
  - name: Install IIS
    ansible.windows.win_feature:
      name: Web-Server
      state: present
    register: win_feature
  - name: Reboot if installing Web-Server feature requires it
    ansible.windows.win_reboot:
    when: win_feature.reboot_required
  - name: Install rest
    ansible.windows.win_feature:
      name: Web-Mgmt-Tools
      name: Web-Mgmt-Console
      name: Web-Ftp-Server
      name: Web-Ftp-Service
      state: present
    register: win_feature
  - name: Reboot win2
    ansible.windows.win_reboot:
  - name: Configure and start FTP
    win_shell: |
      Import-Module WebAdministration
      $ftpsitename = "test2"
      $path = "C:\Users\ansibleuser\Desktop\test2"
      mkdir $path
      New-WebFtpSite -Name $ftpsitename -Port 21 -PhysicalPath $path
      $param = @{
             Path    = 'C:\Users\ansibleuser\Desktop\test2'
             Name    = 'ftpserver.security.authentication.basicauthentication.disabled'
             Value   = $true
             Verbose = $True
      }
  - name: Make sure IIS webserver not running
    win_service:
      name: W3Svc
      state: stopped
  - name: Run FTP
    win_service:
      name: ftpsvc
      state: started
  - name: Download Apache 2.4.46
    win_get_url:
      url: https://www.apachelounge.com/download/VS16/binaries/httpd-2.4.46-win64-VS16.zip
      dest: C:\Users\ansibleuser\Desktop\Apache.zip
  - name: Unzipping Apache
    community.windows.win_unzip:
      src: C:\Users\ansibleuser\Desktop\Apache.zip
      dest: C:\
      delete_archive: yes
  - name: Install Apache
    script: InstallApacheOnWindows.bat
  - name: Deleting Apache default index.html
    ansible.windows.win_file:
      path: C:\Apache24\htdocs\index.html
      state: absent
  - name: Create new website
    win_copy:
      content: "<html><head><title>This is also a website!</title></head><body><h1> This is a webpage as well. But we are using Apache instead of IIS here <img src='https://upload.wikimedia.org/wikipedia/commons/d/d6/Apache_HTTPD.png'></h1><p>This is a paragraph.</p></body></html>"
      dest: C:\Apache24\htdocs\index.html
  - name: Create firewall rule to allow TCP 80 Apache
    community.windows.win_firewall_rule:
      name: Allow Apache
      description: Created by Ansible. Tried without, didnt work.
      program: C:\Apache24\bin\httpd.exe
      localport: 80
      action: allow
      direction: in
      protocol: tcp
      state: present
      enabled: yes
  - name: Run Apache service
    win_service:
      name: Apache2.4
      state: started
